### ISSUE TITLE
Configure bot from docker image

### ISSUE THREAD

**Issue by DailytheNoob** [synzen/Discord.RSS#131]
I followed the steps for installing with docker-compose, here is `docker-compose.yml`:

```
version: '3.3'
services:
    discord.rss:
        container_name: discord-rss
        image: synzen/discord.rss
        environment:
          - DRSS_BOT_TOKEN=[token]
          - DRSS_DATABASE_URI=./database
```

there is no config file created and there is no way to enable the web UI
